import { ResearchViewTable } from "@/types";

export const SACT_table: ResearchViewTable = {
  table: "ONCO_SACT_INT_RESEARCH",
  columns: [
    {
      name: "ETL_ID",
      data_type: "int",
      primary: true,
      max_length: undefined,
      description: "Required",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ETL_DATE",
      data_type: "datetime",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DIRECT_CARE_PUBLISHED_RUNID",
      data_type: "int",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATASET_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 150,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "NDO_RUN_DATE",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "FILE_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 75,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "FILE_PERIOD_START",
      data_type: "nvarchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "FILE_PERIOD_END",
      data_type: "nvarchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "NHS_NUMBER",
      data_type: "varbinary",
      primary: false,
      max_length: 4000,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "LOCAL_PATIENT_IDENTIFIER",
      data_type: "nvarchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "NHS_NUMBER_STATUS",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PERSON_FAMILY_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PERSON_GIVEN_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_OF_BIRTH_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_OF_BIRTH_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_OF_BIRTH_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PERSON_STATED_GENDER_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PATIENT_POSTCODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "LLSOA",
      data_type: "nvarchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "CONSULTANT_GMC_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "CONSULTANT_SPEC_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ORG_ID_CODE_PROVIDER",
      data_type: "nvarchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PRIMARY_DIAGNOSIS",
      data_type: "nvarchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "MORPHOLOGY_ICD_O",
      data_type: "nvarchar",
      primary: false,
      max_length: 7,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DIAGNOSIS_CODE_SNOMED",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ADJUNCTIVE_THERAPY",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "INTENT_OF_TREATMENT",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REGIMEN",
      data_type: "nvarchar",
      primary: false,
      max_length: 150,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "HEIGHT_START_REG",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "WEIGHT_START_OF_REG",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PERF_STATUS_START_REG_AD",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "CO_MORBIDITY_ADJUSTMENT",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_DECISION_TO_TREAT_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_DECISION_TO_TREAT_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DATE_DECISION_TO_TREAT_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_REGIMEN_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_REGIMEN_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_REGIMEN_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "CLINICAL_TRIAL",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "CYCLE_NUMBER",
      data_type: "int",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_CYCLE_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_CYCLE_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "START_DATE_CYCLE_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "WEIGHT_START_CYCLE",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "PERF_STAT_START_CYCLE_AD",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DRUG_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 55,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ACTUAL_DOSE_PER_ADMIN",
      data_type: "nvarchar",
      primary: false,
      max_length: 50,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ADMIN_MEAS_PER_ACTUAL_DOSE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "OT_ADMIN_MEAS_PER_ACTUAL_DOSE",
      data_type: "nvarchar",
      primary: false,
      max_length: 15,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "UNIT_MEAS_SNOMED_CT_DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "SACT_ADMINISTRATION_ROUTE",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ROUTE_ADMIN_SNOMED_CT_DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ADMINISTRATION_DATE_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ADMINISTRATION_DATE_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ADMINISTRATION_DATE_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "ORG_IDENTIFIER_SACT_ADMIN",
      data_type: "nvarchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REG_MOD_DOSE_REDUCTION",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REG_OUT_CUR_COMP_PLAN",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REG_OUT_CUR_N_COMP_AS_PLAN_RES",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "OT_REG_OUT_N_COMP_AS_PLAN_RES",
      data_type: "nvarchar",
      primary: false,
      max_length: 55,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REG_OUT_NON_CURATIVE",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
    {
      name: "REG_OUT_TOXICITY",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "ONCO_SACT_INT_RESEARCH",
    },
  ],
};

export const COSD_table: ResearchViewTable = {
  table: "COSD",
  columns: [
    {
      name: "ETL_ID",
      data_type: "int",
      primary: true,
      max_length: undefined,
      description: "Required",
      table: "COSD",
    },
    {
      name: "ETL_DATE",
      data_type: "datetime",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "SUBMISSION_ID",
      data_type: "varchar",
      primary: false,
      max_length: 36,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ID_SUBMITTING_ORG",
      data_type: "varchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "RECORD_COUNT",
      data_type: "varchar",
      primary: false,
      max_length: 7,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "REPORTING_PERIOD_START_DATE",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "REPORTING_PERIOD_END_DATE",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "FILE_CREATION_DATETIME",
      data_type: "varchar",
      primary: false,
      max_length: 19,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "RECORD_TYPE",
      data_type: "nvarchar",
      primary: false,
      max_length: 50,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "UNIQUE_RECORD_ID",
      data_type: "varchar",
      primary: false,
      max_length: 36,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NHS_NUMBER",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "LOCAL_PATIENT_ID",
      data_type: "varchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NHS_NUM_STAT_CODE",
      data_type: "varchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_BIRTH_DATE",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PROVIDER_ID",
      data_type: "varchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_DIAG_PRIMARY_DIAG_ICD",
      data_type: "varchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_DIAG_TUMOUR_LATERALITY",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_DIAG_DATE_OF_PRIMARY_DIAG_CLIN_AGREED",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DIAG_DIAGNOSIS_CLINICALLY_AGREED",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DIAG_ORIGINAL_PRIMARY_DIAGNOSIS_ICD",
      data_type: "varchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_TYPE1",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_SITE1",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_TYPE2",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_SITE2",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DIAG_PALLIATIVE_CARE_SPECIALIST_SEEN_INDICATOR_CANCER_RECURRENCE",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DIAG_RELAPSE_METHOD_OF_DETECTIO_1",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DIAG_RELAPSE_METHOD_OF_DETECTION_2",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_PROGRESSION_ICD",
      data_type: "varchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_TYPE_PROGRESSION1",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_SITE_PROGRESSION1",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_TYPE_PROGRESSION2",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_METASTATIC_SITE_PROGRESSION2",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_ORIGINAL_MORPHOLOGYICD_O_3",
      data_type: "varchar",
      primary: false,
      max_length: 7,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_ORIGINAL_MORPHOLOGY_SNOMED",
      data_type: "varchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_MORPHOLOGY_ICD_O_3_TRANSFORMATION",
      data_type: "varchar",
      primary: false,
      max_length: 7,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_MORPHOLOGY_SNOMED_TRANSFORMATION",
      data_type: "varchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_SNOMED_VERSION_CURRENT_TRANSFORMATION",
      data_type: "varchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_FAMILY_NAME",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_GIVEN_NAME",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "STREET_ADDRESS_LINE1",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "STREET_ADDRESS_LINE2",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "STREET_ADDRESS_LINE3",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "STREET_ADDRESS_LINE4",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "STREET_ADDRESS_LINE5",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "UNSTRUCTURED_ADDRESS",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "POSTCODE_OF_USUAL_ADDRESS_AT_DIAGNOSIS",
      data_type: "varchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_STATED_GENDER_CODE",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_SEXUAL_ORIENTATION_CODE_AT_DIAGNOSIS",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "GENERAL_MEDICAL_PRACTITIONER_SPECIFIED",
      data_type: "varchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "GENERAL_MEDICAL_PRACTICE_CODE_PATIENT_REGISTRATION",
      data_type: "varchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PERSON_FAMILY_NAME_AT_BIRTH",
      data_type: "varchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ETHNIC_CATEGORY",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ETHNIC_CATEGORY_2021",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_SOURCE_OF_REFERRAL_OP",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_DATE_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_PROF_REG_ISSUER_CODE_CONS_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_PROF_REG_ENTRY_ID_CONS_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 32,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_ORG_SITE_PROV_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_DATE_FIRST_SEEN_CANCER_SPECIALIST",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PP_ORG_SITE_ID_PROV_FIRST_CANCER_SPECIALIST",
      data_type: "varchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_SOURCE_OF_REFERRAL_FOR",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_DATE_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "NPP_ORG_SITE_ID_PROV_FIRST_SEEN",
      data_type: "varchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ORG_SITE_ID_OF_IMAGING",
      data_type: "varchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "PROCEDURE_DATE_CANCER_IMAGING",
      data_type: "varchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "IMAGING_REPORT_TEXT",
      data_type: "varchar",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "IMAGING_CODE_NICIP",
      data_type: "varchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "IMAGING_CODE_SNOWMED_CT",
      data_type: "varchar",
      primary: false,
      max_length: 19,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "CANCER_IMAGING_MODALITY",
      data_type: "varchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "IMAGING_ANATOMICAL_SITE",
      data_type: "varchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ANATOMICAL_SIDE_IMAGING",
      data_type: "varchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "COSD",
    },
    {
      name: "ORGANISATION_SITE_IDENTIFIER_OF_IMAGING2",
      data_type: "varchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "COSD",
    },
  ],
};
