import { ResearchViewTable } from "@/types/table";

export const SACT_table: ResearchViewTable = {
  table: "SACT",
  columns: [
    {
      name: "ETL_ID",
      data_type: "int",
      primary: true,
      max_length: undefined,
      description: "Required",
      table: "SACT",
    },
    {
      name: "ETL_DATE",
      data_type: "datetime",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DIRECT_CARE_PUBLISHED_RUNID",
      data_type: "int",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATASET_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 150,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "NDO_RUN_DATE",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "FILE_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 75,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "FILE_PERIOD_START",
      data_type: "nvarchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "FILE_PERIOD_END",
      data_type: "nvarchar",
      primary: false,
      max_length: 10,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "NHS_NUMBER",
      data_type: "varbinary",
      primary: false,
      max_length: 4000,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "LOCAL_PATIENT_IDENTIFIER",
      data_type: "nvarchar",
      primary: false,
      max_length: 20,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "NHS_NUMBER_STATUS",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PERSON_FAMILY_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PERSON_GIVEN_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 35,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_OF_BIRTH_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_OF_BIRTH_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_OF_BIRTH_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PERSON_STATED_GENDER_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PATIENT_POSTCODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "LLSOA",
      data_type: "nvarchar",
      primary: false,
      max_length: 9,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "CONSULTANT_GMC_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "CONSULTANT_SPEC_CODE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ORG_ID_CODE_PROVIDER",
      data_type: "nvarchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PRIMARY_DIAGNOSIS",
      data_type: "nvarchar",
      primary: false,
      max_length: 6,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "MORPHOLOGY_ICD_O",
      data_type: "nvarchar",
      primary: false,
      max_length: 7,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DIAGNOSIS_CODE_SNOMED",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ADJUNCTIVE_THERAPY",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "INTENT_OF_TREATMENT",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REGIMEN",
      data_type: "nvarchar",
      primary: false,
      max_length: 150,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "HEIGHT_START_REG",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "WEIGHT_START_OF_REG",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PERF_STATUS_START_REG_AD",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "CO_MORBIDITY_ADJUSTMENT",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_DECISION_TO_TREAT_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_DECISION_TO_TREAT_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DATE_DECISION_TO_TREAT_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_REGIMEN_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_REGIMEN_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_REGIMEN_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "CLINICAL_TRIAL",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "CYCLE_NUMBER",
      data_type: "int",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_CYCLE_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_CYCLE_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "START_DATE_CYCLE_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "WEIGHT_START_CYCLE",
      data_type: "float",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "PERF_STAT_START_CYCLE_AD",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DRUG_NAME",
      data_type: "nvarchar",
      primary: false,
      max_length: 55,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ACTUAL_DOSE_PER_ADMIN",
      data_type: "nvarchar",
      primary: false,
      max_length: 50,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ADMIN_MEAS_PER_ACTUAL_DOSE",
      data_type: "nvarchar",
      primary: false,
      max_length: 8,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "OT_ADMIN_MEAS_PER_ACTUAL_DOSE",
      data_type: "nvarchar",
      primary: false,
      max_length: 15,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "UNIT_MEAS_SNOMED_CT_DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "SACT_ADMINISTRATION_ROUTE",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ROUTE_ADMIN_SNOMED_CT_DM_D",
      data_type: "nvarchar",
      primary: false,
      max_length: 18,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ADMINISTRATION_DATE_YEAR",
      data_type: "nvarchar",
      primary: false,
      max_length: 4,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ADMINISTRATION_DATE_MONTH",
      data_type: "nvarchar",
      primary: false,
      max_length: 2,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ADMINISTRATION_DATE_MID_MONTH",
      data_type: "date",
      primary: false,
      max_length: undefined,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "ORG_IDENTIFIER_SACT_ADMIN",
      data_type: "nvarchar",
      primary: false,
      max_length: 5,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REG_MOD_DOSE_REDUCTION",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REG_OUT_CUR_COMP_PLAN",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REG_OUT_CUR_N_COMP_AS_PLAN_RES",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "OT_REG_OUT_N_COMP_AS_PLAN_RES",
      data_type: "nvarchar",
      primary: false,
      max_length: 55,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REG_OUT_NON_CURATIVE",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
    {
      name: "REG_OUT_TOXICITY",
      data_type: "nvarchar",
      primary: false,
      max_length: 1,
      description: "Optional",
      table: "SACT",
    },
  ],
};

export const COSD_table: ResearchViewTable = {
  table: "COSD",
  columns: [
    {
      name: "Coming soon",
      data_type: "Coming soon",
      primary: true,
      max_length: 0,
      description: "Coming soon",
      table: "COSD",
    },
  ],
};
