name: Deploy Test function app to Azure

on:
  push:
    branches:
      - main

    paths:
      - "workers-test/**"

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./workers-test"
  PYTHON_VERSION: "3.11"

jobs:
  build-and-publish-workers:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.29"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "./workers-test/pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Install requirements
        run: uv pip install -r ./workers-test/requirements.txt
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Build package
        run: uv build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: functionsapp-test
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          include-hidden-files: true

  # Deploy Workers Production
  deploy-workers-production:
    runs-on: ubuntu-latest
    needs: build-and-publish-workers
    environment: production
    env:
      SCM_DO_BUILD_DURING_DEPLOYMENT: true
      ENABLE_ORYX_BUILD: true

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          path: functionsapp-test
          name: functionsapp-test

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1.5.1
        id: fa
        with:
          app-name: ${{ vars.AZURE_FUNCTIONS_NAME_TEST }}
          slot-name: "production"
          package: ${{ github.workspace }}/functionsapp-test
          publish-profile: ${{ secrets.AZURE_FUNCAPP_PUBLISH_PROFILE_TEST  }}
