name: Deploy UI app to Azure

on:
  push:
    branches:
      - main
    paths:
      - "./ui-app"

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./ui-app"
  NODE_VERSION: 20

jobs:
  build-and-publish-next-app:
    runs-on: ubuntu-latest
    environment: dev
    env:
      BACKEND_ORIGIN: ${{ secrets.BACKEND_ORIGIN }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        run: |
          npm i --workspaces=false
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Caching node modules should be done better
      - name: Cache .next/cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH  }}/.next/cache
          key: nextjs | $(Agent.OS) | ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json

      - name: Build
        run: npm run build --workspaces=false
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Copy Static Assets
        run: |
          cp -r .next/static .next/standalone/.next/
          cp -r public .next/standalone/
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish webapp artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/.next/standalone
          name: uiwebapp
          include-hidden-files: true

  # Deploy Next.js Client App Production
  deploy-next-production:
    runs-on: ubuntu-latest
    needs: [build-and-publish-next-app]
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          path: uiwebapp
          name: uiwebapp

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NEXT_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_NEXT_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/uiwebapp
