name: Deploy function app to Azure

on:
  release:
    types: [released]

    paths:
      - "workers/**"

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./workers"
  PYTHON_VERSION: "3.11"

jobs:
  build-and-publish-workers:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Install Poetry"
        uses: snok/install-poetry@v1
        with:
          plugins: poetry-plugin-export

      - name: "Resolve Project Dependencies Using Poetry"
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          poetry config virtualenvs.create false
          poetry export --format requirements.txt --output requirements.txt --without-hashes
          popd
        shell: bash

      - name: "Install Dependencies Using Pip"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: functionsapp
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          include-hidden-files: true

  # Deploy Workers Production
  deploy-workers-production:
    runs-on: ubuntu-latest
    needs: build-and-publish-workers
    environment: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          path: functionsapp
          name: functionsapp

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1.5.1
        id: fa
        with:
          app-name: ${{ vars.AZURE_FUNCTIONS_NAME }}
          slot-name: "production"
          package: ${{ github.workspace }}/functionsapp
          publish-profile: ${{ secrets.AZURE_FUNCAPP_PUBLISH_PROFILE  }}
